### ISSUE TITLE
Question about mcprotocol.js writing to X017

### ISSUE THREAD

**Issue by armour23** [plcpeople/mcprotocol#2]
Hi

Firstly, thank you for developing this interface. It is very useful. 

I have an FX3U-64M with an FX-ENET-ADP. I was testing the writing of X017 and based on the manual for FX-ENET-ADP the MC code should be:
00 FF 0A 00 11 00 00 00 20 58 01 00 10

However, mcprotocol.js seems to be writing the code:
00 FF 0A 00 0F 00 00 00 20 58 01 00 10

and it works. Can you let me know how does "X017" translate to the fifth hex character to be "0F" instead of "11"? "11" is the hex representation of 17. 

Thanks!

**Comment by armour23** [comment]
Hi there

I found the answer - turns out that the X inputs are from X000 - X007, X010 - X017, X020 - X027, and X030 - X037. Their corresponding MC codes are in running order in hexadecimal. 

Thanks for reading!

**Comment by plcpeople** [comment]
Great - it's good to hear the software is working well for you.
